### ISSUE TITLE
This palette cannot be added in Cloud deployment

### ISSUE THREAD

**Issue by janlouda** [ibmets/node-red-bluemix-nodes#71]
Once you deploy Node-RED via the Node-RED starter in IBM Cloud catalog, you are not able to install this palette. In the install tab next to the node-red-bluemix-nodes it says "conflict" instead of the "install" button.

I wanted to install it because of the weather service but was not able to.

**Comment by knolleary** [comment]
Hi @janlouda 

We removed this collection of nodes from the palette as we believed them to be largely redundant as the services they connect to are no longer provided in the cloud catalog.

Have you already used these nodes with the weather service in another instance?

The conflict is because those module provides alternative TCP/UDP nodes which conflict with the core palette. I could republish this module with those nodes removed so it can be installed with out conflict... but I want to understand if the Weather nodes are still useful or not.

**Comment by janlouda** [comment]
You are right, the service is no longer offered in the catalog :( Pity, we used it for education purposes. I have my old instance provisioned however if new instances cannot be deployed there is no point for this node.

**Comment by knolleary** [comment]
I know.... a real shame as you could do some cool things with it. I'm sorry for the inconvenience.
